use flawchk_core::CveEntry;

pub fn load_builtin_cve_database() -> Vec<CveEntry> {
    vec![
        CveEntry {
            cve_id: "CVE-2026-72014".to_string(),
            title: "Linux Kernel DRBD Payload Size Out-of-Bounds Memory Corruption".to_string(),
            package_name: "linux-kernel".to_string(),
            affected_version_range: ">= 6.0, < 6.12.18".to_string(),
            fixed_version: "6.12.18".to_string(),
            cvss_score: 8.8,
            attack_vector: "Network".to_string(),
            privileges_required: "Low".to_string(),
            subsystem: "DRBD (Distributed Replicated Block Device)".to_string(),
            required_module: Some("drbd".to_string()),
            required_service: None,
            description: "A vulnerability in the Linux kernel DRBD subsystem allows remote authenticated peers to trigger an out-of-bounds memory write via forged payload sizes.".to_string(),
            temporary_mitigation: Some("Unload the DRBD kernel module (`modprobe -r drbd`) or block DRBD TCP port 7788 in iptables/nftables if DRBD is not actively required.".to_string()),
            references: vec![
                "https://www.kernel.org/doc/Documentation/admin-guide/cve.rst".to_string(),
                "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git".to_string(),
            ],
        },
        CveEntry {
            cve_id: "CVE-2026-72317".to_string(),
            title: "Linux Kernel SUNRPC TLS Connection Worker Use-After-Free".to_string(),
            package_name: "linux-kernel".to_string(),
            affected_version_range: ">= 6.1, < 6.13.4".to_string(),
            fixed_version: "6.13.4".to_string(),
            cvss_score: 8.1,
            attack_vector: "Network".to_string(),
            privileges_required: "None".to_string(),
            subsystem: "SUNRPC / TLS".to_string(),
            required_module: Some("sunrpc".to_string()),
            required_service: Some("nfsd".to_string()),
            description: "A TLS connection worker in the SUNRPC subsystem could access an unpinned rpc_clnt object after its original lifetime ended, leading to memory corruption.".to_string(),
            temporary_mitigation: Some("Disable RPC-over-TLS transport or restrict NFS/SUNRPC ports (2049, 111) to trusted internal subnets.".to_string()),
            references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2026-72317".to_string()],
        },
        CveEntry {
            cve_id: "CVE-2026-71980".to_string(),
            title: "Linux Kernel Bluetooth HCI Packet Parser Buffer Overflow".to_string(),
            package_name: "linux-kernel".to_string(),
            affected_version_range: ">= 5.15, < 6.12.10".to_string(),
            fixed_version: "6.12.10".to_string(),
            cvss_score: 7.5,
            attack_vector: "Adjacent".to_string(),
            privileges_required: "None".to_string(),
            subsystem: "Bluetooth HCI".to_string(),
            required_module: Some("bluetooth".to_string()),
            required_service: None,
            description: "Malformed Bluetooth HCI event packets can trigger a buffer overflow in kernel memory when processing adjacent wireless signals.".to_string(),
            temporary_mitigation: Some("Disable Bluetooth interface (`rfkill block bluetooth` or blacklist the `bluetooth` kernel module in `/etc/modprobe.d/`.".to_string()),
            references: vec!["https://wiki.gentoo.org/wiki/Bluetooth".to_string()],
        },
        CveEntry {
            cve_id: "CVE-2026-72105".to_string(),
            title: "Linux Kernel ksmbd SMB3 Server Remote Code Execution".to_string(),
            package_name: "linux-kernel".to_string(),
            affected_version_range: ">= 5.15, < 6.12.14".to_string(),
            fixed_version: "6.12.14".to_string(),
            cvss_score: 9.6,
            attack_vector: "Network".to_string(),
            privileges_required: "None".to_string(),
            subsystem: "ksmbd (Kernel SMB Server)".to_string(),
            required_module: Some("ksmbd".to_string()),
            required_service: Some("ksmbd".to_string()),
            description: "In-kernel SMB3 server (ksmbd) fails to validate NTLM authentication packet bounds, enabling unauthenticated remote code execution with kernel privileges.".to_string(),
            temporary_mitigation: Some("Stop and unload ksmbd service (`ksmbd.mount` or `modprobe -r ksmbd`) and use user-space Samba (`smbd`) temporarily.".to_string()),
            references: vec!["https://www.kernel.org/doc/html/latest/filesystems/cifs/ksmbd.html".to_string()],
        },
        CveEntry {
            cve_id: "CVE-2024-6387".to_string(),
            title: "OpenSSH Server Signal Handler Race Condition (regreSSHion)".to_string(),
            package_name: "openssh".to_string(),
            affected_version_range: ">= 8.5p1, < 9.8p1".to_string(),
            fixed_version: "9.8p1".to_string(),
            cvss_score: 8.1,
            attack_vector: "Network".to_string(),
            privileges_required: "None".to_string(),
            subsystem: "OpenSSH Daemon".to_string(),
            required_module: None,
            required_service: Some("sshd".to_string()),
            description: "A signal handler race condition in sshd allows unauthenticated remote code execution as root on glibc-based Linux systems.".to_string(),
            temporary_mitigation: Some("Set `LoginGraceTime 0` in `/etc/ssh/sshd_config` (note: this mitigates remote RCE but enables Denial of Service if connections are exhausted).".to_string()),
            references: vec!["https://www.qualys.com/2024/07/01/cve-2024-6387/regresshion.php".to_string()],
        },
    ]
}
